export const dataBerita =  [
  
    {
      "judul": "Kanwil Kemenkum Maluku Serahkan Naskah Akademik dan Rancangan Perda Cadangan Pangan SBB",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-serahkan-naskah-akademik-dan-rancangan-perda-cadangan-pangan-sbb",
      "instagram": "https://www.instagram.com/p/DPQjDVdk7MT/?igsh=Nm8zazMzYnFqbmo=",
      "twitter": "https://x.com/kemenkummaluku/status/1973294389909922151?t=6hd3V0iPTemqQex_UNilTg&s=19",
      "facebook": "https://m.facebook.com/story.php?story_fbid=pfbid0GwZLk8rvNiUswysDj8wWUVG1dttzGVr7bXyXcZZVKTaZA3ZGwcb5p2XTjxqSmNsbl&id=100062597052913&mibextid=ZbWKwL",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dcf3b1c925c4201818aec3/kanwil-kemenkum-maluku-serahkan-naskah-akademik-dan-rancangan-perda-cadangan-pangan-sbb",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/01/kanwil-kemenkum-maluku-serahkan-naskah-akademik-dan-rancangan-perda-cadangan-pangan-sbb/",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "PPPK Resmi Bergabung, Kementerian Hukum Dapat Suntikan Energi Baru",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru",
      "instagram": "https://www.instagram.com/p/DPQqjbak9OE/?igsh=bGl0a3F5Y3ZrdmJs",
      "twitter": "https://x.com/kemenkummaluku/status/1973309882364551307?t=jjXAIUpRD6ZB38ZAM9is4Q&s=19",
      "facebook": "https://m.facebook.com/story.php?story_fbid=pfbid08qr1JTkFTR5UJjnvhzPjVV5F9hDVyRHadGMqcp8MsxArMEyKHg6zWTgNEPd5KatUl&id=100062597052913&mibextid=ZbWKwL",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dd0ca334777c4adc24c012/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/01/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/01/pppk-bergabung-kanwil-kemenkum-maluku-dapat-suntikan-energi-baru/",
      "rri": "https://rri.co.id/ambon/daerah/1874241/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru"
    },
    {
      "judul": "Peringati Hari Kesaktian Pancasila, Kanwil Kemenkum Maluku Teguhkan Semangat Nasionalisme",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/peringati-hari-kesaktian-pancasila-kanwil-kemenkum-maluku-teguhkan-semangat-nasionalisme",
      "instagram": "https://www.instagram.com/p/DPQcph4E0wl/?igsh=ZGR6empxZ2ZiMjZ0",
      "twitter": "https://x.com/kemenkummaluku/status/1973278899598655736?t=u2KbE89iD00APdfFvgyHng&s=19",
      "facebook": "https://m.facebook.com/story.php?story_fbid=pfbid02xi5Gg2KnGbB9SxUp63uKQ1ukgg7UDVmhsW9PKiRorXLZv3ZSVJdq3mzdR4pngK4kl&id=100062597052913&mibextid=ZbWKwL",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dc974a34777c35d562d352/peringati-hari-kesaktian-pancasila-kanwil-kemenkum-maluku-teguhkan-semangat-nasionalisme",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/01/peringati-hari-kesaktian-pancasila-kanwil-kemenkum-maluku-teguhkan-semangat-nasionalisme/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/01/peringati-hari-kesaktian-pancasila-ini-penegasan-kanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/daerah/1874036/kanwil-kemenkum-teguhkan-semangat-nasionalisme-di-hari-kesaktian-pancasila"
    },
    {
      "judul": "Percepat Pembentukan Posbankum Desa dan Kelurahan, Kanwil Kemenkum Maluku Singgahi SBB",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/percepat-pembentukan-posbankum-desa-dan-kelurahan-kanwil-kemenkum-maluku-singgahi-sbb",
      "instagram": "https://www.instagram.com/p/DPQiUg0EzXB/?igsh=a2ZzbzcxNnV6d3Rq",
      "twitter": "https://x.com/kemenkummaluku/status/1973293024076767355?t=UPyLPupm-3vFqwxjInDO_w&s=19",
      "facebook": "https://www.facebook.com/share/p/169M4YjTqH/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dcdb6034777c2c2f014945/percepat-pembentukan-posbankum-desa-dan-kelurahan-kanwil-kemenkum-maluku-singgahi-sbb",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/01/percepat-pembentukan-posbankum-desa-dan-kelurahan-kepala-kanwil-kemenkum-maluku-sambangi-sbb/",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Optimalisasi Anggaran: Kemenkum Maluku Ikut Penyusunan RPD Triwulan IV Secara Virtual",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd-triwulan-iv-secara-virtual",
      "instagram": "https://www.instagram.com/p/DPQq0qIE4RS/?igsh=MTl0aG16eHNmYWl2dA==",
      "twitter": "https://x.com/kemenkummaluku/status/1973310101319831684?s=19",
      "facebook": "https://www.facebook.com/share/p/16Bv7h9HdU/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dd1beded64151bb43cbb94/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd-triwulan-iv-secara-virtual",
      "terasmaluku": "https://terasmaluku.com/ekonomi/2025/10/01/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd-triwulan-iv/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/01/optimalisasi-anggaran-ini-harapan-kakanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/daerah/1874263/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd"
    },
    {
      "judul": "Posbankum Masuk Desa: Kolaborasi Nyata Kemenkum Maluku dan Gubernur",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/posbankum-masuk-desa-kolaborasi-nyata-kemenkum-maluku-dan-gubernur",
      "instagram": "https://www.instagram.com/p/DPS19N0kksd/?igsh=bGJuaTkxeXFmN3dv",
      "twitter": "https://x.com/kemenkummaluku/status/1973615538866896921?t=NN37bF30upuXaVCTDdmjaA&s=19",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de18b134777c27a621abe3/posbankum-masuk-desa-kolaborasi-nyata-kemenkum-maluku-dan-gubernur",
      "facebook": "https://www.facebook.com/share/p/1Ab26yR5ne/",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/02/posbankum-masuk-desa-kolaborasi-nyata-gubernur-dan-kemenkum-maluku/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/posbankum-masuk-desa-di-maluku/",
      "rri": "https://rri.co.id/ambon/hukum/1876240/posbankum-masuk-desa-kolaborasi-nyata-kemenkum-maluku-dan-gubernur",
      "id": 2
    },
    {
      "judul": "Saiful Sahri Serahkan SK PPPK, Tegaskan Pentingnya Integritas Aparatur",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/saiful-sahri-serahkan-sk-pppk-tegaskan-pentingnya-integritas-aparatur",
      "instagram": "https://www.instagram.com/p/DPS10LqkpHg/?igsh=MXF4MXhrYzJlc3Exdg==",
      "twitter": "https://x.com/kemenkummaluku/status/1973615430184181770?t=noYd1Lb2t1iFqcLjZH0ePQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1A19qGKEb5/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ddff95ed641523f0242a56/saiful-sahri-serahkan-sk-pppk-tegaskan-pentingnya-integritas-aparatur",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/02/saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/pppk-kanwil-kemenkum-maluku-tak-sekadar-bertugas/",
      "rri": "https://rri.co.id/ambon/daerah/1876869/sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "id": 3
    },
    {
      "judul": "Berikan Penguatan, Saiful Sahri PPPK Bukan Sekadar Bertugas, Tapi Menghidupkan Semangat Baru",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/berikan-penguatan-saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "instagram": "https://www.instagram.com/p/DPS2ElhEvGO/?igsh=aTNpNDBpZmlraDNm",
      "twitter": "https://x.com/kemenkummaluku/status/1973615651442082298?t=jeHu-QdyxiBD8Ky6NyGhIQ&s=19",
      "facebook": "https://www.facebook.com/share/p/19m7MRS9Uo/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de270d34777c0820506094/berikan-penguatan-saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/02/saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/pppk-kanwil-kemenkum-maluku-tak-sekadar-bertugas/",
      "rri": "https://rri.co.id/ambon/daerah/1876869/sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "id": 4
    },
    {
      "judul": "Tertib Administrasi, Ratusan Arsip Fidusia dan Fasilitatif Kemenkum Maluku Dimusnahkan",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/tertib-administrasi-ratusan-arsip-fidusia-dan-fasilitatif-kemenkum-maluku-dimusnahkan",
      "instagram": "https://www.instagram.com/p/DPTHYQUksJV/?igsh=bTZkYW9xdGJ5NWZj",
      "twitter": "https://x.com/kemenkummaluku/status/1973658138479042835?t=PmBHbNat_18jfbSi9Jyq2g&s=19",
      "facebook": "https://www.facebook.com/share/p/1Dsiu6MSXa/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de39f8c925c476a7621f62/tertib-administrasi-ratusan-arsip-fidusia-dan-fasilitatif-kemenkum-maluku-dimusnahkan",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/ratusan-arsip-fidusia-fasilitatif-kanwil-kemenkum-maluku-dimusnahkan/",
      "rri": "https://rri.co.id/ambon/daerah/1876878/ratusan-arsip-fidusia-fasilitatif-kemenkum-maluku-dimusnahkan"
    },
    {
      "judul": "Kemenkum Maluku Fokus Tekan Deviasi Anggaran di Triwulan IV: RPD Disusun Lebih Realistis dan Tepat Sasaran",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-fokus-tekan-deviasi-anggaran-di-triwulan-iv-rpd-disusun-lebih-realistis-dan-tepat-sasaran",
      "instagram": "https://www.instagram.com/p/DPTHuDOkgGn/?igsh=Mzh3ZDZ3N3Nlb2lm",
      "twitter": "https://x.com/kemenkummaluku/status/1973658138479042835?t=PmBHbNat_18jfbSi9Jyq2g&s=19",
      "facebook": "https://www.facebook.com/share/p/17MPCSe1Du/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de48a634777c11a502a295/kemenkum-maluku-fokus-tekan-deviasi-anggaran-di-triwulan-iv-rpd-disusun-lebih-realistis-dan-tepat-sasaran",
      "terasmaluku": "https://rri.co.id/ambon/daerah/1876889/rencana-penarikan-dana-disusun-lebih-realistis-tepat-sasaran",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/kanwil-kemenkum-maluku-fokus-tekan-deviasi-anggaran-di-triwulan-iv/",
      "rri": ""
    },
    {
      "judul": "Kanwil Kemenkum Maluku Ikuti Sosialisasi KUHP Nasional",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional",
      "instagram": "https://www.instagram.com/p/DPTIq5sEtZa/?igsh=MjZ1c3NpODdpd3V0",
      "twitter": "https://x.com/kemenkummaluku/status/1973658519011467699?t=IB9IsCbvFlqAXwkmO4FF5g&s=19",
      "facebook": "https://www.facebook.com/share/p/1D1ZKmrAgr/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de58aa34777c68553eb103/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/02/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional/",
      "rri": ""
    },
    {
      "judul": "Kemenkum Maluku Ikuti Sosialisasi Pelayanan Publik Ramah Kelompok Rentan",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-ikuti-sosialisasi-pelayanan-publik-ramah-kelompok-rentan",
      "instagram": "https://www.instagram.com/p/DPTeRZ_kmEY/?igsh=ZTJlbzFua3kzdTB4*",
      "twitter": "https://x.com/kemenkummaluku/status/1973704104171192653?t=1NXAX1xI-GtmhTeKmPi1wA&s=19",
      "facebook": "https://www.facebook.com/share/p/1AKzKQTz6m/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de6bc534777c5da621a8d3/kemenkum-maluku-ikuti-sosialisasi-pelayanan-publik-ramah-kelompok-rentan",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1876900/kemenkum-maluku-ikuti-sosialisasi-pelayanan-publik-ramah-kelompok-rentan"
    },{
      "judul": "Hari Pertama Maluku Manggurebe : Kemenkum Maluku Hadirkan Pelayanan Hukum Langsung ke Masyarakat",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/hari-pertama-maluku-manggurebe-kemenkum-maluku-hadirkan-pelayanan-hukum-langsung-ke-masyarakat",
      "instagram": "https://www.instagram.com/p/DPTp-lMkju4/?igsh=MTB5aXN1emdvd2RseQ== ",
      "twitter": "https://x.com/kemenkummaluku/status/1973729529085800591?t=8uMfGdSP5fll4FaTUsED_g&s=19",
      "facebook": "https://www.facebook.com/share/p/1MaqBiJfUi/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de7f12ed64156ca260cc93/hari-pertama-maluku-manggurebe-kemenkum-maluku-hadirkan-pelayanan-hukum-langsung-ke-masyarakat",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Kanwil Kemenkum Maluku Dukung Sinergi Ekonomi Kreatif pada Pembukaan Maluku Manggurebe 2025",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-dukung-sinergi-ekonomi-kreatif-pada-pembukaan-maluku-manggurebe-2025",
      "instagram": "https://www.instagram.com/p/DPWos0QktvQ/?igsh=djM4d2x6d3Bza3o4",
      "twitter": "https://x.com/kemenkummaluku/status/1974152360466526261?t=BfiuBnXxpXs0MH8wqKxYiQ&s=19",
      "facebook": "https://www.facebook.com/share/p/17HY1AKZo2/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68df9ffec925c436647bb3d5/kanwil-kemenkum-maluku-dukung-sinergi-ekonomi-kreatif-pada-pembukaan-maluku-manggurebe-2025",
      "terasmaluku": "https://terasmaluku.com/ekonomi/2025/10/03/kanwil-kemenkum-maluku-dukung-sinergi-ekonomi-kreatif-pada-maluku-manggurebe-2025/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1878417/kanwil-kemenkum-dukung-sinergi-ekonomi-kreatif-maluku-manggurebe-2025"
    },
    {
      "judul": "Booth Kemenkum Maluku di Maluku Manggurebe 2025 Dikunjungi Deputi BI dan Kepala OJK Maluku",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/booth-kemenkum-maluku-di-maluku-manggurebe-2025-dikunjungi-deputi-bi-dan-kepala-ojk-maluku",
      "instagram": "https://www.instagram.com/p/DPWpKqGEnuC/?igsh=bTdzeGhhcjd3Z3ly",
      "twitter": "https://x.com/kemenkummaluku/status/1974152555891691935?t=f-sGV54_QyxIAwxau_P_nA&s=19",
      "facebook": "https://www.facebook.com/share/p/1EzqX2Dkmi/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dfaec6ed64151bd752b8a2/booth-kemenkum-maluku-di-maluku-manggurebe-2025-dikunjungi-deputi-bi-dan-kepala-ojk-maluku",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/03/booth-kanwil-kemenkum-di-maluku-manggurebe-2025-dikunjungi-deputi-bi-kepala-ojk/",
      "rri": "https://rri.co.id/ambon/daerah/1878625/booth-kemenkum-dikunjungi-deputi-bi-kepala-ojk"
    },
     {
      "judul": "Booth Layanan Kemenkum Maluku Ramai Dikunjungi di Hari Kedua Maluku Manggurebe 2025",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/booth-layanan-kemenkum-maluku-ramai-dikunjungi-di-hari-kedua-maluku-manggurebe-2025",
      "instagram": "https://www.instagram.com/p/DPWpYLxkjia/?igsh=cXdkYjZucDVlYzZo",
      "twitter": "https://x.com/kemenkummaluku/status/1974153021706940693?t=TYXUXk9-z2W7wPrJUS-t9w&s=19",
      "facebook": "https://www.facebook.com/share/p/17J3BjjWKd/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dfe9ed34777c5c654b12a4/booth-layanan-kemenkum-maluku-ramai-dikunjungi-di-hari-kedua-maluku-manggurebe-2025",
      "terasmaluku": "https://terasmaluku.com/ekonomi/2025/10/03/booth-layanan-kemenkum-maluku-ramai-dikunjungi-warga-di-maluku-manggurebe-2025/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/03/booth-layanan-kanwil-kemenkum-ramai-dikunjungi-di-hari-kedua-maluku-manggurebe-2025/",
      "rri": "https://rri.co.id/ambon/daerah/1878639/booth-maluku-manggurebe-kemenkum-ramai-dikunjungi-hari-kedua"
    },
    {
      "judul": "Semangat Kolaborasi, Kakanwil Kementerian Hukum Maluku Sambut Kedatangan Komisi XIII DPR RI",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/semangat-kolaborasi-kakanwil-kementerian-hukum-maluku-sambut-kedatangan-komisi-xiii-dpr-ri",
      "instagram": "https://www.instagram.com/p/DPWpk38krsm/?igsh=MXVjdXQwMDRybGh3bw==",
      "twitter": "https://x.com/kemenkummaluku/status/1974153317698904442?t=KmwyUwMf_NGfdhFZeHaAHw&s=19",
      "facebook": "https://www.facebook.com/share/p/15g9kXRWmB/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e000e434777c577a092062/semangat-kolaborasi-kakanwil-kementerian-hukum-maluku-sambut-kedatangan-komisi-xiii-dpr-ri",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/03/kakanwil-kementerian-hukum-maluku-sambut-kedatangan-komisi-xiii-dpr-ri/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1879330/kakanwil-kemenkum-maluku-sambut-kedatangan-komisi-xiiidpr-ri"
    },
    {
      "judul": "Kakanwil Kemenkum Maluku Paparkan Isu Strategis di Hadapan Komisi XIII DPR RI",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kakanwil-kemenkum-maluku-paparkan-isu-strategis-di-hadapan-komisi-xiii-dpr-ri",
      "instagram": "https://www.instagram.com/p/DPWqBqGkvkG/?igsh=dWEwcm5pM2UyMnl3",
      "twitter": "https://x.com/kemenkummaluku/status/1974153683429658850?t=T0isZSrr912tyKg9F7LX_Q&s=19",
      "facebook": "https://www.facebook.com/share/p/1GDE69i3Bi/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e00efb34777c56fd1cbdf2/kakanwil-kemenkum-maluku-paparkan-isu-strategis-di-hadapan-komisi-xiii-dpr-ri",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/04/kakanwil-kemenkum-maluku-paparkan-isu-strategis-di-hadapan-komisi-xiii-dpr-ri/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1879911/kakanwil-kemenkum-maluku-paparkan-isu-strategis-ke-komisi-xiii-dpr-ri"
    },
    {
      "judul": "16 Kali Berturut-Turut Raih WTP, Kemenkumham Tutup Perjalanan Dengan Catatan Emas",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/16-kali-berturut-turut-raih-wtp-kemenkumham-tutup-perjalanan-dengan-catatan-emas",
      "instagram": "https://www.instagram.com/p/DPW4vK5k_FK/?img_index=2&igsh=MWtzdndjYzQzZWcwMA==",
      "twitter": "https://x.com/kemenkummaluku/status/1974186025460322623?t=OQUlz_K1nyXqSZmeTm-pkA&s=19",
      "facebook": "https://www.facebook.com/share/p/1GMx6ut2Ax/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e01f3a34777c71d44808d4/16-kali-berturut-turut-raih-wtp-kemenkumham-tutup-perjalanan-dengan-catatan-emas",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "WTP ke-16, Akhir 'Manis' Kemenkumham Sebelum Transformasi Kelembagaan",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/wtp-ke-16-akhir-manis-kemenkumham-sebelum-transformasi-kelembagaan",
      "instagram": "https://www.instagram.com/p/DPW5m2Hk3Fn/?img_index=1&igsh=c3VqbXN5ZjlhejY4",
      "twitter": "https://x.com/kemenkummaluku/status/1974186025460322623?t=Fp7yU0yqmWEHJGYKbI6Rkg&s=19",
      "facebook": "https://www.facebook.com/share/p/19rmuboj9b/",
      "kompasiana": "",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Saiful Sahri Dampingi Komisi XIII DPR RI Tinjau Upt Pemasyarakatan dan Imigrasi di Ambon",
      "tanggal": "4-10-2025",
      "hari": 4,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/saiful-sahri-dampingi-komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi-di-ambon",
      "instagram": "https://www.instagram.com/p/DPYbNhREva8/?igsh=MW5vMGI5bjVkb2szZg==",
      "twitter": "https://x.com/kemenkummaluku/status/1974402112202395763?t=6hOvk2pjlSvq6AtCm7YBgw&s=19",
      "facebook": "https://www.facebook.com/share/p/1BnEXVk5mp/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e0da6c34777c47911a5bc5/saiful-sahri-dampingi-komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi-di-ambon",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/04/saiful-sahri-dampingi-komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/04/kakanwil-kemenkum-maluku-dampingi-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi-di-ambon/",
      "rri": "https://rri.co.id/ambon/daerah/1880828/komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-imigrasi-ambon"
    },
    {
      "judul": "Anggota DPR RI Kunjungi Booth Layanan Kemenkum Maluku di Acara Maluku Manggurebe 2025",
      "tanggal": "4-10-2025",
      "hari": 4,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/anggota-dpr-ri-kunjungi-booth-layanan-kemenkum-maluku-di-acara-maluku-manggurebe-2025",
      "instagram": "https://www.instagram.com/p/DPYbtV0EnRV/?igsh=eTQ1YnN6MzdzOGo5",
      "twitter": "https://x.com/kemenkummaluku/status/1974402317660414403?t=lDiwwwKg-pK3xcuxbDhd_g&s=19",
      "facebook": "https://www.facebook.com/share/p/1BQj3vhEkN/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e0e906ed64157bef753905/anggota-dpr-ri-kunjungi-booth-layanan-kemenkum-maluku-di-acara-maluku-manggurebe-2025",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/04/anggota-dpr-ri-kunjungi-booth-layanan-kanwil-kemenkum-di-maluku-manggurebe-2025/",
      "rri": "https://rri.co.id/ambon/daerah/1880734/anggota-dprri-kunjungibooth-layanan-kemenkum-di-maluku-manggurebe"
    },
    {
      "judul": "RUU Pidana Mati Disorot: Kemenkum Maluku Ikuti Webinar Bahas Tata Cara Pelaksanaan Yang Berkeadilan",
      "tanggal": "8-10-2025",
      "hari": 8,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/ruu-pidana-mati-disorot-kemenkum-maluku-ikuti-webinar-bahas-tata-cara-pelaksanaan-yang-berkeadilan",
      "instagram": "https://www.instagram.com/p/DPiq_7eku1W/?igsh=N3ZzdTduZm5yczEz",
      "twitter": "https://x.com/kemenkummaluku/status/1975843068600574175?t=OcIYKNwiMM0JxphbP77E-g&s=19",
      "facebook": "https://www.facebook.com/share/p/178ckuU3ke/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e6205b34777c21c41b4782/ruu-pidana-mati-disorot-kemenkum-maluku-ikuti-webinar-bahas-tata-cara-pelaksanaan-yang-berkeadilan",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/09/ruu-pidana-mati-disorot-kemenkum-maluku-ikuti-webinar-bahas-tata-cara-pelaksanaan-yang-berkeadilan/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/08/kanwil-kemenkum-maluku-ikuti-webinar-bahas-ruu-pidana-mati/",
      "rri": "https://rri.co.id/ambon/daerah/1888608/kemenkum-maluku-ikut-webinar-ruu-pidana-mati"
    },
    {
      "judul": "Saiful Sahri Temui Kapolda Maluku, Bahas Posbankum Hingga Penyelesaian Konflik Sosial",
      "tanggal": "8-10-2025",
      "hari": 8,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/saiful-sahri-temui-kapolda-maluku-bahas-posbankum-hingga-penyelesaian-konflik-sosial",
      "instagram": "https://www.instagram.com/p/DPiK4hSEp9K/?igsh=ZTByMWt2aWhhN3M4",
      "twitter": "https://x.com/kemenkummaluku/status/1975772643413664042?t=kMNO6j3EqWDNQYgqsmpxgA&s=19",
      "facebook": "https://www.facebook.com/share/p/1K4HuhJsLc/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e5dba4ed641527234abd74/saiful-sahri-temui-kapolda-maluku-bahas-posbankum-hingga-penyelesaian-konflik-sosial",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/08/saiful-sahri-temui-kapolda-maluku-bahas-posbankum-hingga-penyelesaian-konflik-sosial/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/08/kakanwil-kemenkum-maluku-temui-kapolda-ini-yang-dibahas/",
      "rri": "https://rri.co.id/ambon/daerah/1887974/saiful-sahri-temui-kapolda-maluku-bahas-posbankum"
    },
    {
      "judul": "Resmi Jadi Peacemaker, 11 Pemimpin Desa Terima Sertifikat NLP dari Kemenkum Maluku",
      "tanggal": "8-10-2025",
      "hari": 8,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/resmi-jadi-peacemaker-11-pemimpin-desa-terima-sertifikat-nlp-dari-kemenkum-maluku",
      "instagram": "https://www.instagram.com/p/DPihED2EkzS/?igsh=bjIxc2Nmcjk0M2xw",
      "twitter": "https://x.com/kemenkummaluku/status/1975821897578553771?t=1pFWgQwl6ykigSTptcQ07Q&s=19",
      "facebook": "https://www.facebook.com/share/p/1K55r3X1oP/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e60b80c925c4770953d392/resmi-jadi-peacemaker-11-pemimpin-desa-terima-sertifikat-nlp-dari-kemenkum-maluku",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/08/11-kades-lurahterima-sertifikat-nlp-dari-kanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/hukum/1888589/resmi-jadi-peacemaker-11-pemimpin-desa-terima-sertifikat-nlp"
    },
    {
      "judul": " Kemenkum Maluku Ikuti Forum Nasional Penguatan Tata Kelola Kolaboratif Beneficial Ownership",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-ikuti-forum-nasional-penguatan-tata-kelola-kolaboratif-beneficial-ownership",
      "instagram": "https://www.instagram.com/p/DPdi0vhEh4u/?igsh=anNrcHFua2F2MThu",
      "twitter": "https://x.com/kemenkummaluku/status/1975121250415739079?t=pLHMc-LYInXAvIB_xsQKcw&s=19",
      "facebook": "https://www.facebook.com/share/p/171hQNeYEX/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e3804bc925c44c074601b2/kemenkum-maluku-ikuti-forum-nasional-penguatan-tata-kelola-kolaboratif-beneficial-ownership",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/06/kakanwil-kemenkum-maluku-ikuti-forum-nasional-penguatan-tata-kelola-kolaboratif/",
      "rri": ""
    },
    {
      "judul": "Apel Pagi Tak Lagi Biasa: Inovasi, Otak Sehat, dan WTP Jadi Sorotan Saiful Sahri",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/apel-pagi-tak-lagi-biasa-inovasi-otak-sehat-dan-wtp-jadi-sorotan-saiful-sahri",
      "instagram": "https://www.instagram.com/p/DPdCQIyEuZw/?igsh=ZDJrd2NmcXpnNmoy",
      "twitter": "https://x.com/kemenkummaluku/status/1975056261441089637?t=ashxRqVNAXpO_mteNktLGA&s=19",
      "facebook": "https://www.facebook.com/share/p/16cUaY5fVe/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e31d0e34777c498c151253/apel-pagi-tak-lagi-biasa-inovasi-otak-sehat-dan-wtp-jadi-sorotan-saiful-sahri",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/06/apel-pagi-tak-lagi-biasa-inovasi-otak-sehat-dan-wtp-jadi-sorotan-saiful-sahri/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/06/apel-pagi-tak-lagi-biasa-ini-penegasan-kakanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/daerah/1883607/inovasi-otak-sehat-wtp-disorot-saiful-sahri"
    },
    {
      "judul": "Dedikasi Berbuah Apresiasi: Kemenkum Maluku Anugerahkan Penghargaan dan Kenaikan Pangkat",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/dedikasi-berbuah-apresiasi-kemenkum-maluku-anugerahkan-penghargaan-dan-kenaikan-pangkat",
      "instagram": "https://www.instagram.com/p/DPdDeZ6krJu/?igsh=MWVhdGZ6NTN2NmRhNA==",
      "twitter": "https://x.com/kemenkummaluku/status/1975056945955721271?t=83-uIwd_3T-0xAzbIvBhNQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1BQ83zc7KT/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e3443934777c06cc671bf2/dedikasi-berbuah-apresiasi-kemenkum-maluku-anugerahkan-penghargaan-dan-kenaikan-pangkat",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": " Rapat Evaluasi Posbankum Soroti Strategi Percepatan dan Kendala Lapangan",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/rapat-evaluasi-posbankum-soroti-strategi-percepatan-dan-kendala-lapangan",
      "instagram": "https://www.instagram.com/p/DPdT8cJkm1n/?igsh=MXZocmFhczVidXc2OA==",
      "twitter": "https://x.com/kemenkummaluku/status/1975089505653903668?t=eo3YvsxsxHs4x0Mg0pfUjQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1A787yVRYp/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e35b1fed64156283164cf2/rapat-evaluasi-posbankum-soroti-strategi-percepatan-dan-kendala-lapangan",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/06/rapat-evaluasi-posbankum-kanwil-kemenkum-maluku-soroti-strategi-percepatan-kendala-lapangan/",
      "rri": "https://rri.co.id/ambon/hukum/1883826/rapat-evaluasi-posbankum-soroti-strategi-percepatan-dan-kendala-lapangan"
    },
    {
      "judul": "Era Baru Transparansi Korporasi Dimulai, Kemenkum Luncurkan Aplikasi Untuk Berantas Kejahatan Keuangan",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/era-baru-transparansi-korporasi-dimulai-kemenkum-luncurkan-aplikasi-untuk-berantas-kejahatan-keuangan",
      "instagram": "https://www.instagram.com/p/DPdUMa3khuz/?igsh=MTB1cnpxeWJ0cHp1NQ==",
      "twitter": "https://x.com/kemenkummaluku/status/1975089793907474627?t=lyWyQKxcWPDDOtiv-aBD9w&s=19",
      "facebook": "https://www.facebook.com/share/p/1BHentQ2Sg/",
      "kompasiana": "",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Komitmen Maluku Dalam Evaluasi Bantuan Hukum Nasional: Menjangkau Lebih Banyak, Melayani Lebih Baik",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/komitmen-maluku-dalam-evaluasi-bantuan-hukum-nasional-menjangkau-lebih-banyak-melayani-lebih-baik",
      "instagram": "https://www.instagram.com/p/DPdv3y3Eqc5/?igsh=MXdiMmZyMHVxYnAwNg==",
      "twitter": "https://x.com/kemenkummaluku/status/1975151205501595901?t=9j6pvl8BcM_Wilid0grz6g&s=19",
      "facebook": "https://www.facebook.com/share/p/1CZ2NQTQgM/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e395d1ed641513d736cc33/komitmen-maluku-dalam-evaluasi-bantuan-hukum-nasional-menjangkau-lebih-banyak-melayani-lebih-baik",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1884388/komitmen-kemenkum-maluku-evaluasi-bantuan-hukum-nasional-melayani-lebih-baik"
    },
    {
      "judul": "Kemenkum Maluku Perkuat Komitmen Transparansi Data Pemilik Manfaat Korporasi",
      "tanggal": "6-10-2025",
      "hari": 6,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-perkuat-komitmen-transparansi-data-pemilik-manfaat-korporasi",
      "instagram": "https://www.instagram.com/p/DPd0m2hkiOM/?igsh=bmd6M2hheDE2dnA5",
      "twitter": "https://x.com/kemenkummaluku/status/1975160351017857389?t=i1kxq7MoHuJPK4cWC3Ra9g&s=19",
      "facebook": "https://www.facebook.com/share/p/17XWFtCVdv/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e3a44e34777c64bc0fce14/kemenkum-maluku-perkuat-komitmen-transparansi-data-pemilik-manfaat-korporasi",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Merajut Hukum, Menyatukan Daerah: Kemenkum Maluku Dorong Harmoni Regulasi di Maluku Tengah",
      "tanggal": "9-10-2025",
      "hari": 9,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/merajut-hukum-menyatukan-daerah-kemenkum-maluku-dorong-harmoni-regulasi-di-maluku-tengah",
      "instagram": "https://www.instagram.com/p/DPlRnFhkq-Y/?igsh=cTd1NzYxZ3RhemJq",
      "twitter": "https://x.com/kemenkummaluku/status/1976210878698750281?t=Ue4hPx_yWOKK5FyryuFa-A&s=19",
      "facebook": "https://www.facebook.com/share/p/17K38vkTfU/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e765ef34777c215441e5f2/merajut-hukum-menyatukan-daerah-kemenkum-maluku-dorong-harmoni-regulasi-di-maluku-tengah",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/09/merajut-hukum-menyatukan-daerah-kemenkum-maluku-dorong-harmoni-regulasi-di-maluku-tengah/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/09/kanwil-kemenkum-maluku-dorong-harmoni-regulasi-di-malteng/",
      "rri": "https://rri.co.id/ambon/daerah/1890964/merajut-hukum-kemenkum-maluku-dorong-harmoni-regulasi-di-malteng"
    },
    {
      "judul": "Kemenkum Maluku Mantapkan Langkah, Rapatkan Barisan Jelang Diskusi Strategi Kebijakan",
      "tanggal": "9-10-2025",
      "hari": 9,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-mantapkan-langkah-rapatkan-barisan-jelang-diskusi-strategi-kebijakan",
      "instagram": "https://www.instagram.com/p/DPlSLudkmCo/?igsh=N3BieHA0bXdob3By",
      "twitter": "https://x.com/kemenkummaluku/status/1976211220211609772?t=GVaLX5jNWTEaI6HUwBlPmA&s=19",
      "facebook": "https://www.facebook.com/share/p/1YPGqfhZBt/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e78cc8ed64152fd70ce782/kemenkum-maluku-mantapkan-langkah-rapatkan-barisan-jelang-diskusi-strategi-kebijakan",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/09/kemenkum-maluku-mantapkan-langkah-rapatkan-barisan-jelang-diskusi-strategi-kebijakan/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1891085/kemenkum-maluku-mantapkan-langkah-jelang-diskusi-strategi-kebijakan"
    },
    {
      "judul": "DWP Kemenkum Maluku Sinergikan Kesehatan dan Kebersamaan Dalam Pertemuan Rutin",
      "tanggal": "9-10-2025",
      "hari": 9,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/dwp-kemenkum-maluku-sinergikan-kesehatan-dan-kebersamaan-dalam-pertemuan-rutin",
      "instagram": "https://www.instagram.com/p/DPlRXXtkhhE/?igsh=cXUydXN6Z3JpNXNk",
      "twitter": "https://x.com/kemenkummaluku/status/1976210713401340364?t=1MZ28JmYr0RKMst9L-rKQQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1BQVZgMafV/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e7549dc925c4231110d5b3/dwp-kemenkum-maluku-sinergikan-kesehatan-dan-kebersamaan-dalam-pertemuan-rutin",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/09/dwp-kanwil-kemenkum-maluku-sosialisasi-kesehatan/",
      "rri": "https://rri.co.id/ambon/daerah/1890941/dwp-kemenkum-maluku-sinergi-kesehatan-kebersamaan"
    },
    {
      "judul": "Hukum Sebagai Fondasi, Daerah Sebagai Rumah: SBT dan Kemenkum Maluku Perkuat Sinergi",
      "tanggal": "9-10-2025",
      "hari": 9,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/hukum-sebagai-fondasi-daerah-sebagai-rumah-sbt-dan-kemenkum-maluku-perkuat-sinergi",
      "instagram": "https://www.instagram.com/p/DPlR7NLkhS-/?igsh=Ym50MnV3dmtnYjJm",
      "twitter": "https://x.com/kemenkummaluku/status/1976211055144742953?t=ZhSAKJu_csj9aEnYMBOOxg&s=19",
      "facebook": "https://www.facebook.com/share/p/1CTmQzHvnZ/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e7750734777c4ec730ed73/hukum-sebagai-fondasi-daerah-sebagai-rumah-sbt-dan-kemenkum-maluku-perkuat-sinergi",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/09/hukum-sebagai-fondasi-daerah-sebagai-rumah-pemkab-sbt-dan-kemenkum-maluku-perkuat-sinergi/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1890993/perkuat-pondasi-hukum-wakil-bupati-sbt-temui-kakanwil-kemenkum-maluku"
    },
    {
      "judul": "Silaturahmi Strategis: Malteng dan Kemenkum Maluku Satukan Langkah",
      "tanggal": "9-10-2025",
      "hari": 9,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/silaturahmi-strategis-malteng-dan-kemenkum-maluku-satukan-langkah",
      "instagram": "https://www.instagram.com/p/DPlg1XykqS5/?igsh=MTlnNmNxc3NocjN4Yw==",
      "twitter": "https://x.com/kemenkummaluku/status/1976252593040130384?t=YyjLJGeazhbHfs8j2MnMDA&s=19",
      "facebook": "https://www.facebook.com/share/p/1BbHWj96wy/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e7a24b34777c3808060b52/silaturahmi-strategis-malteng-dan-kemenkum-maluku-satukan-langkah",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1891209/silaturahmi-strategis-malteng-dan-kemenkum-maluku-satukan-langkah"
    },
    {
      "judul": "SK Kepengurusan Diterima, Sekjen PSI Sebut Pelayanan Kemenkum Super Cepat",
      "tanggal": "10-10-2025",
      "hari": 10,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/sk-kepengurusan-diterima-sekjen-psi-sebut-pelayanan-kemenkum-super-cepat",
      "instagram": "https://www.instagram.com/p/DPnuS8Fkj09/?igsh=bGs4bGxhZ2YxNDQ0",
      "twitter": "https://x.com/kemenkummaluku/status/1976553830935585236?t=UiIcm0qOaRdvhQM67sq1jA&s=19",
      "facebook": "https://www.facebook.com/share/p/17BwycJgzT/",
      "kompasiana": "",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Langkah Emas Dua Kabupaten: Buru dan Bursel Raih Penghargaan 100% Pos Bankum Desa",
      "tanggal": "12-10-2025",
      "hari": 12,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/langkah-emas-dua-kabupaten-buru-dan-bursel-raih-penghargaan-100-pos-bankum-desa",
      "instagram": "https://www.instagram.com/p/DPs1UEJktIH/?igsh=MWEyM2wxNWRncHMzeg==",
      "twitter": "https://x.com/kemenkummaluku/status/1977274926345384064?t=vNChJwC8eO3JjGQJpvUxjg&s=19",
      "facebook": "https://www.facebook.com/share/p/1BNKopJFjQ/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68eb2685c925c452733c8b92/langkah-emas-dua-kabupaten-buru-dan-bursel-raih-penghargaan-100-pos-bankum-desa",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/12/kabupaten-buru-dan-bursel-raih-penghargaan-100-pos-bankum-desa/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/12/buru-bursel-raih-penghargaan-100-bentuk-posbankum-desa/",
      "rri": "https://rri.co.id/ambon/daerah/1896355/buru-bursel-raih-penghargaan-pos-bankum-desa"
    },
    {
      "judul": "Minggu Bersejarah di Buru, Saiful Sahri Serahkan Tabloid Tabaos Edisi Oktober",
      "tanggal": "12-10-2025",
      "hari": 12,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/minggu-bersejarah-di-buru-saiful-sahri-serahkan-tabloid-tabaos-edisi-oktober",
      "instagram": "https://www.instagram.com/p/DPsWfqxkmR3/?igsh=MXRmYW8xNG8zZjhsMQ==",
      "twitter": "https://x.com/kemenkummaluku/status/1977205099962532116?t=0tFeOvnHE7tN0tA4qo03nQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1CSsqVmnGV/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68eb11cfed64155d170b9ee2/minggu-bersejarah-di-buru-saiful-sahri-serahkan-tabloid-tabaos-edisi-oktober",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/12/kanwil-kemenkum-maluku-pemkab-buru-bersinergi/",
      "rri": "https://rri.co.id/ambon/daerah/1896307/saiful-sahri-serahkan-tabloid-tabaos-edisi-oktober"
    },
    {
      "judul": "Negara Hadir di Jantung Bupolo: Kakanwil Kemenkum Maluku Hadiri HUT Buru Ke-26",
      "tanggal": "12-10-2025",
      "hari": 12,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/negara-hadir-di-jantung-bupolo-kakanwil-kemenkum-maluku-hadiri-hut-buru-ke-26",
      "instagram": "https://www.instagram.com/p/DPs1gT1Eo2o/?igsh=YjdyZ2xyaXY4NWc0",
      "twitter": "https://x.com/kemenkummaluku/status/1977275072630210601?t=njGyfNhNcqdunMjWy31EIQ&s=19",
      "facebook": "https://www.facebook.com/share/p/16X9ej8Jnu/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68eb4efa34777c32bd1e0553/negara-hadir-di-jantung-bupolo-kakanwil-kemenkum-maluku-hadiri-hut-buru-ke-26",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/12/negara-hadir-di-jantung-bupolo-kakanwil-kemenkum-maluku-hadiri-hut-buru-ke-26/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/12/kakanwil-kemenkum-maluku-hadiri-hut-ke-26-buru/",
      "rri": "https://rri.co.id/ambon/daerah/1896369/kakanwil-kemenkum-maluku-hadiri-hut-kabipaten-buru"
    },
    {
      "judul": "Gema Semangat Buru Ke-26: Kakanwil Kemenkum Maluku Serahkan Piala di Tengah Sorak Sorai Warga",
      "tanggal": "12-10-2025",
      "hari": 12,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/gema-semangat-buru-ke-26-kakanwil-kemenkum-maluku-serahkan-piala-di-tengah-sorak-sorai-warga",
      "instagram": "https://www.instagram.com/p/DPs1sMykjHD/?igsh=MWszZHN5Mm43eDd2",
      "twitter": "https://x.com/kemenkummaluku/status/1977275232319861092?t=tHUXEdNDkt4aZIJyJ-kf7A&s=19",
      "facebook": "https://www.facebook.com/share/p/17RCc5sugF/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68eb8e8ded64154ff714b712/gema-semangat-buru-ke-26-kakanwil-kemenkum-maluku-serahkan-piala-di-tengah-sorak-sorai-warga",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1896382/kakanwil-kemenkum-maluku-serahkan-piala-pemenang-lomba-hut-buru"
    },
    {
      "judul": "Kemenkum Maluku Hadiri Virtual Peresmian Posbankum dan Pelatihan Paralegal Maluku Utara",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-hadiri-virtual-peresmian-posbankum-dan-pelatihan-paralegal-maluku-utara",
      "instagram": "https://www.instagram.com/p/DPvnT0jEhQ-/?igsh=N3VmOWprNmlvNXAw",
      "twitter": "https://x.com/kemenkummaluku/status/1977664440209379742?t=LABLef8_SXlhjkD-ram72A&s=19",
      "facebook": "https://www.facebook.com/share/p/1CNcPg2HKD/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ecf30d34777c13b3746745/kemenkum-maluku-hadiri-virtual-peresmian-posbankum-dan-pelatihan-paralegal-maluku-utara",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/13/maluku-utara-jadi-provinsi-pertama-di-kti-yang-100-posbankum-desa-terbentuk/",
      "rri": "https://rri.co.id/ambon/hukum/1898520/kemenkum-maluku-hadiri-virtual-peresmian-posbankum-pelatihan-paralegal-malut"
    },
    {
      "judul": "Apel Pagi ASN Berbuah Prestasi, Kota Ambon Ukir Rekor Posbankum 100%",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/apel-pagi-asn-berbuah-prestasi-kota-ambon-ukir-rekor-posbankum-100",
      "instagram": "https://www.instagram.com/p/DPu3ciqEjaa/?igsh=MWJvaWZsNXQ4dWRkdw==",
      "twitter": "https://x.com/kemenkummaluku/status/1977558910895820844?t=pEiUBYn6b4LZ25c1_eOpDw&s=19",
      "facebook": "https://www.facebook.com/share/p/17FYgopni9/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ec5f50a2184665784c61b2/apel-pagi-asn-berbuah-prestasi-kota-ambon-ukir-rekor-posbankum-100",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/13/kota-ambon-ukir-rekor-posbankum-100-persen/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/13/kota-ambon-ukir-rekor-posbankum-desa-100/",
      "rri": "https://rri.co.id/ambon/daerah/1897522/kota-ambon-ukir-rekor-posbankum-100-persen"
    },
    {
      "judul": "Bukan Sekadar Rutinitas: Apel Pagi Jadi Cermin Integritas ASN Kemenkum Maluku",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/bukan-sekadar-rutinitas-apel-pagi-jadi-cermin-integritas-asn-kemenkum-maluku",
      "instagram": "https://www.instagram.com/p/DPvkPzJEuD1/?igsh=MWRzMnhsNXMwNHM2aA==",
      "twitter": "https://x.com/kemenkummaluku/status/1977659129843101743?t=AZvQ9RHUEsDW3hbEJHgNDA&s=19",
      "facebook": "https://www.facebook.com/share/p/1DarLDDqps/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ecb127c925c44d7e740d94/bukan-sekadar-rutinitas-apel-pagi-jadi-cermin-integritas-asn-kemenkum-maluku",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/13/apel-pagi-jadi-cermin-integritas-asn-kanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/daerah/1897997/apel-pagi-jadi-cermin-integritas-asn-kemenkum-maluku"
    },
    {
      "judul": "Kemenkum Maluku Perkuat Akuntabilitas Melalui Pengisian Matrik Pemantauan dan Evaluasi Perjanjian Kinerja",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-perkuat-akuntabilitas-melalui-pengisian-matrik-pemantauan-dan-evaluasi-perjanjian-kinerja",
      "instagram": "https://www.instagram.com/p/DPvkndQEgYk/?igsh=NXhrZWo3cHM5bzYy",
      "twitter": "https://x.com/kemenkummaluku/status/1977659299611734456?t=Sv5GHiWGLdYTDwvT32OXYA&s=19",
      "facebook": "https://www.facebook.com/share/p/1S9iZg4GLo/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ecbf89d30d2855b917f892/kemenkum-maluku-perkuat-akuntabilitas-melalui-pengisian-matrik-pemantauan-dan-evaluasi-perjanjian-kinerja",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/13/kemenkum-maluku-perkuat-akuntabilitas-lewat-pengisian-matrik-pemantauan-dan-evaluasi-perjanjian-kinerja/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/13/kanwil-kemenkum-maluku-perkuat-akuntabilitas/",
      "rri": "https://rri.co.id/ambon/daerah/1898012/kemenkum-maluku-perkuat-akuntabilitas-perjanjian-kinerja"
    },
    {
      "judul": "Kanwil Kemenkum Maluku Siap Dukung Penyelenggaraan Amboina Fair Chapter 5 Tahun 2025",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-siap-dukung-penyelenggaraan-amboina-fair-chapter-5-tahun-2025",
      "instagram": "https://www.instagram.com/p/DPvkx2wEnYQ/?igsh=eHByamZ3Z2FzcXZp",
      "twitter": "https://x.com/kemenkummaluku/status/1977659583696105807?t=Qo4G7LZ0Q1RhWD-2i4f74Q&s=19",
      "facebook": "https://www.facebook.com/share/p/1798pWECCp/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ece2f0a4f06614980e33b3/kanwil-kemenkum-maluku-siap-dukung-penyelenggaraan-amboina-fair-chapter-5-tahun-2025",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/13/kanwil-kemenkum-maluku-siap-dukung-penyelenggaraan-amboina-fair-chapter-5/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/13/kanwil-kemenkum-maluku-dukung-amboina-fair-chapter-5/",
      "rri": "https://rri.co.id/ambon/daerah/1898030/kanwil-kemenkum-maluku-dukung-penyelenggaraan-amboina-fair-chapter"
    },
    {
      "judul": "Kolaborasi Kemenkum Maluku dan Pemprov, Wujudkan Siskamling Berbasis Keadilan di Desa dan Kelurahan",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kolaborasi-kemenkum-maluku-dan-pemprov-wujudkan-siskamling-berbasis-keadilan-di-desa-dan-kelurahan",
      "instagram": "https://www.instagram.com/p/DPv4-1pErBz/?igsh=MTUyMmdzYXJwc2FiYw==",
      "twitter": "https://x.com/kemenkummaluku/status/1977703449522323720?t=RR5ffRdsOV8sUrnDtMIqnw&s=19",
      "facebook": "https://www.facebook.com/share/p/1A1rECiW6J/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ed0146c925c43d7b6f66e6/kolaborasi-kemenkum-maluku-dan-pemprov-wujudkan-siskamling-berbasis-keadilan-di-desa-dan-kelurahan",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "DPRD Maluku dan Kementerian Hukum Maluku Gelar Rapat Harmonisasi Empat Ranperda Inisiatif",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/dprd-maluku-dan-kementerian-hukum-maluku-gelar-rapat-harmonisasi-empat-ranperda-inisiatif",
      "instagram": "https://www.instagram.com/p/DPv91AzEk8C/?igsh=MW82Z2UwOXVpcTY1eA==",
      "twitter": "https://x.com/kemenkummaluku/status/1977714180611322129?t=Hsg0Yk9edHlg5f6X_vtXaA&s=19",
      "facebook": "https://www.facebook.com/share/p/1FrypdppSu/",
      "kompasiana": "",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1899638/dprd-maluku-kemenkum-rapat-harmonisasi-empat-ranperda-inisiatif"
    },
    {
      "judul": "Tabloid Tabaos Diserahkan Langsung, DPRD Maluku Apresiasi Langkah Cerdas Kemenkum Maluku",
      "tanggal": "13-10-2025",
      "hari": 13,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/tabloid-tabaos-diserahkan-langsung-dprd-maluku-apresiasi-langkah-cerdas-kemenkum-maluku",
      "instagram": "https://www.instagram.com/p/DPv7JxdEtZv/?igsh=MWZ0Y3RmajlrN2Vtbg==",
      "twitter": "https://x.com/kemenkummaluku/status/1977732120068911535?t=-LMkcOeP_9BsGOx7k-z1PQ&s=19",
      "facebook": "https://www.facebook.com/share/p/17TbWhDGJW/",
      "kompasiana": "",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1899659/serahkan-tabloid-tabaos-dprd-maluku-apresiasi-kemenkum"
    },
    {
      "judul": "Warisan Lokal Mendunia: Kemenkum Maluku Dorong Perlindungan Indikasi Geografis Lewat Dialog Strategis",
      "tanggal": "14-10-2025",
      "hari": 14,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/warisan-lokal-mendunia-kemenkum-maluku-dorong-perlindungan-indikasi-geografis-lewat-dialog-strategis",
      "instagram": "https://www.instagram.com/p/DPyPU7YEqPK/?igsh=eTJmcnJoODViemxt",
      "twitter": "https://x.com/kemenkummaluku/status/1978036322435584395?t=4ZOibOYbzHQSRRVcg9hxTw&s=19",
      "facebook": "https://www.facebook.com/share/p/1DFZFpHAKx/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ee056e34777c09cc69c2a4/warisan-lokal-mendunia-kemenkum-maluku-dorong-perlindungan-indikasi-geografis-lewat-dialog-strategis",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/14/warisan-lokal-mendunia-kemenkum-maluku-dorong-perlindungan-indikasi-geografis/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/14/kakanwil-kemenkum-maluku-regulasi-indikasi-geografis-lindungi-produk-lokal/",
      "rri": "https://rri.co.id/ambon/daerah/1900275/kemenkum-maluku-dorong-perlindungan-indikasi-geografis"
    },
    {
      "judul": "Sambung Rasa, Bangun Asa: Balai Diklat Sulut dan Kemenkum Maluku Satukan Langkah",
      "tanggal": "14-10-2025",
      "hari": 14,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/sambung-rasa-bangun-asa-balai-diklat-sulut-dan-kemenkum-maluku-satukan-langkah",
      "instagram": "https://www.instagram.com/p/DPyPuBckk9T/?igsh=Y2YzZ3RtanBsbnBy",
      "twitter": "https://x.com/kemenkummaluku/status/1978036644595835334?t=wG3kn5QCf6Tlg7Thr3LP5g&s=19",
      "facebook": "https://www.facebook.com/share/p/15ZxEpTQG6/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ee159234777c3e551c0ba2/sambung-rasa-bangun-asa-balai-diklat-sulut-dan-kemenkum-maluku-satukan-langkah",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/14/sambung-rasa-bangun-asa-balai-diklat-sulut-dan-kemenkum-maluku-satukan-langkah/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/14/balai-diklat-sulut-kanwil-kemenkum-maluku-satukan-langkah/",
      "rri": "https://rri.co.id/ambon/daerah/1900294/balai-diklat-sulut-dan-kemenkum-maluku-satukan-langkah"
    },
    {
      "judul": "Kanwil Kemenkum Maluku dan Balai Diklat Sulut Sinergi Jaga Kualitas ASN Lewat Monev CPNS",
      "tanggal": "14-10-2025",
      "hari": 14,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-dan-balai-diklat-sulut-sinergi-jaga-kualitas-asn-lewat-monev-cpns",
      "instagram": "https://www.instagram.com/p/DPyP4nHEvML/?igsh=ZmI5ZjhncDB0bGM0",
      "twitter": "https://x.com/kemenkummaluku/status/1978036933835063801?t=CKDN_Sr0o0UZREqEOKGd1w&s=19",
      "facebook": "https://www.facebook.com/share/p/1FfVV5x5Ve/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ee2500ed64155ddd1383f4/kanwil-kemenkum-maluku-dan-balai-diklat-sulut-sinergi-jaga-kualitas-asn-lewat-monev-cpns",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1900294/balai-diklat-sulut-dan-kemenkum-maluku-satukan-langkah"
    },
    {
      "judul": "Dorong Transparansi Layanan KI, BPKP Kunjungi Kanwil Kemenkum Maluku",
      "tanggal": "14-10-2025",
      "hari": 14,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/dorong-transparansi-layanan-ki-bpkp-kunjungi-kanwil-kemenkum-maluku",
      "instagram": "https://www.instagram.com/p/DPyQXTVEtEq/?igsh=ZTVpbGhzYmk1Ynhs",
      "twitter": "https://x.com/kemenkummaluku/status/1978037186931949602?t=C09_iaOS0goP4NVRFRfyQQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1BYANzKcop/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ee35ea7dd9622dab1b4852/dorong-transparansi-layanan-ki-bpkp-kunjungi-kanwil-kemenkum-maluku",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1900389/dorong-transparansi-layanan-ki-bpkp-kunjungi-kanwil-kemenkum-maluku"
    }
    
  ]