export const dataBerita =  [
  
    {
      "judul": "Kanwil Kemenkum Maluku Serahkan Naskah Akademik dan Rancangan Perda Cadangan Pangan SBB",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-serahkan-naskah-akademik-dan-rancangan-perda-cadangan-pangan-sbb",
      "instagram": "https://www.instagram.com/p/DPQjDVdk7MT/?igsh=Nm8zazMzYnFqbmo=",
      "twitter": "https://x.com/kemenkummaluku/status/1973294389909922151?t=6hd3V0iPTemqQex_UNilTg&s=19",
      "facebook": "https://m.facebook.com/story.php?story_fbid=pfbid0GwZLk8rvNiUswysDj8wWUVG1dttzGVr7bXyXcZZVKTaZA3ZGwcb5p2XTjxqSmNsbl&id=100062597052913&mibextid=ZbWKwL",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dcf3b1c925c4201818aec3/kanwil-kemenkum-maluku-serahkan-naskah-akademik-dan-rancangan-perda-cadangan-pangan-sbb",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/01/kanwil-kemenkum-maluku-serahkan-naskah-akademik-dan-rancangan-perda-cadangan-pangan-sbb/",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "PPPK Resmi Bergabung, Kementerian Hukum Dapat Suntikan Energi Baru",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru",
      "instagram": "https://www.instagram.com/p/DPQqjbak9OE/?igsh=bGl0a3F5Y3ZrdmJs",
      "twitter": "https://x.com/kemenkummaluku/status/1973309882364551307?t=jjXAIUpRD6ZB38ZAM9is4Q&s=19",
      "facebook": "https://m.facebook.com/story.php?story_fbid=pfbid08qr1JTkFTR5UJjnvhzPjVV5F9hDVyRHadGMqcp8MsxArMEyKHg6zWTgNEPd5KatUl&id=100062597052913&mibextid=ZbWKwL",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dd0ca334777c4adc24c012/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/01/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/01/pppk-bergabung-kanwil-kemenkum-maluku-dapat-suntikan-energi-baru/",
      "rri": "https://rri.co.id/ambon/daerah/1874241/pppk-resmi-bergabung-kementerian-hukum-dapat-suntikan-energi-baru"
    },
    {
      "judul": "Peringati Hari Kesaktian Pancasila, Kanwil Kemenkum Maluku Teguhkan Semangat Nasionalisme",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/peringati-hari-kesaktian-pancasila-kanwil-kemenkum-maluku-teguhkan-semangat-nasionalisme",
      "instagram": "https://www.instagram.com/p/DPQcph4E0wl/?igsh=ZGR6empxZ2ZiMjZ0",
      "twitter": "https://x.com/kemenkummaluku/status/1973278899598655736?t=u2KbE89iD00APdfFvgyHng&s=19",
      "facebook": "https://m.facebook.com/story.php?story_fbid=pfbid02xi5Gg2KnGbB9SxUp63uKQ1ukgg7UDVmhsW9PKiRorXLZv3ZSVJdq3mzdR4pngK4kl&id=100062597052913&mibextid=ZbWKwL",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dc974a34777c35d562d352/peringati-hari-kesaktian-pancasila-kanwil-kemenkum-maluku-teguhkan-semangat-nasionalisme",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/01/peringati-hari-kesaktian-pancasila-kanwil-kemenkum-maluku-teguhkan-semangat-nasionalisme/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/01/peringati-hari-kesaktian-pancasila-ini-penegasan-kanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/daerah/1874036/kanwil-kemenkum-teguhkan-semangat-nasionalisme-di-hari-kesaktian-pancasila"
    },
    {
      "judul": "Percepat Pembentukan Posbankum Desa dan Kelurahan, Kanwil Kemenkum Maluku Singgahi SBB",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/percepat-pembentukan-posbankum-desa-dan-kelurahan-kanwil-kemenkum-maluku-singgahi-sbb",
      "instagram": "https://www.instagram.com/p/DPQiUg0EzXB/?igsh=a2ZzbzcxNnV6d3Rq",
      "twitter": "https://x.com/kemenkummaluku/status/1973293024076767355?t=UPyLPupm-3vFqwxjInDO_w&s=19",
      "facebook": "https://www.facebook.com/share/p/169M4YjTqH/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dcdb6034777c2c2f014945/percepat-pembentukan-posbankum-desa-dan-kelurahan-kanwil-kemenkum-maluku-singgahi-sbb",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/01/percepat-pembentukan-posbankum-desa-dan-kelurahan-kepala-kanwil-kemenkum-maluku-sambangi-sbb/",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Optimalisasi Anggaran: Kemenkum Maluku Ikut Penyusunan RPD Triwulan IV Secara Virtual",
      "tanggal": "1-10-2025",
      "hari": 1,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd-triwulan-iv-secara-virtual",
      "instagram": "https://www.instagram.com/p/DPQq0qIE4RS/?igsh=MTl0aG16eHNmYWl2dA==",
      "twitter": "https://x.com/kemenkummaluku/status/1973310101319831684?s=19",
      "facebook": "https://www.facebook.com/share/p/16Bv7h9HdU/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dd1beded64151bb43cbb94/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd-triwulan-iv-secara-virtual",
      "terasmaluku": "https://terasmaluku.com/ekonomi/2025/10/01/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd-triwulan-iv/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/01/optimalisasi-anggaran-ini-harapan-kakanwil-kemenkum-maluku/",
      "rri": "https://rri.co.id/ambon/daerah/1874263/optimalisasi-anggaran-kemenkum-maluku-ikut-penyusunan-rpd"
    },
    {
      "judul": "Posbankum Masuk Desa: Kolaborasi Nyata Kemenkum Maluku dan Gubernur",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/posbankum-masuk-desa-kolaborasi-nyata-kemenkum-maluku-dan-gubernur",
      "instagram": "https://www.instagram.com/p/DPS19N0kksd/?igsh=bGJuaTkxeXFmN3dv",
      "twitter": "https://x.com/kemenkummaluku/status/1973615538866896921?t=NN37bF30upuXaVCTDdmjaA&s=19",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de18b134777c27a621abe3/posbankum-masuk-desa-kolaborasi-nyata-kemenkum-maluku-dan-gubernur",
      "facebook": "https://www.facebook.com/share/p/1Ab26yR5ne/",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/02/posbankum-masuk-desa-kolaborasi-nyata-gubernur-dan-kemenkum-maluku/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/posbankum-masuk-desa-di-maluku/",
      "rri": "https://rri.co.id/ambon/hukum/1876240/posbankum-masuk-desa-kolaborasi-nyata-kemenkum-maluku-dan-gubernur",
      "id": 2
    },
    {
      "judul": "Saiful Sahri Serahkan SK PPPK, Tegaskan Pentingnya Integritas Aparatur",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/saiful-sahri-serahkan-sk-pppk-tegaskan-pentingnya-integritas-aparatur",
      "instagram": "https://www.instagram.com/p/DPS10LqkpHg/?igsh=MXF4MXhrYzJlc3Exdg==",
      "twitter": "https://x.com/kemenkummaluku/status/1973615430184181770?t=noYd1Lb2t1iFqcLjZH0ePQ&s=19",
      "facebook": "https://www.facebook.com/share/p/1A19qGKEb5/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68ddff95ed641523f0242a56/saiful-sahri-serahkan-sk-pppk-tegaskan-pentingnya-integritas-aparatur",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/02/saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/pppk-kanwil-kemenkum-maluku-tak-sekadar-bertugas/",
      "rri": "https://rri.co.id/ambon/daerah/1876869/sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "id": 3
    },
    {
      "judul": "Berikan Penguatan, Saiful Sahri PPPK Bukan Sekadar Bertugas, Tapi Menghidupkan Semangat Baru",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/berikan-penguatan-saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "instagram": "https://www.instagram.com/p/DPS2ElhEvGO/?igsh=aTNpNDBpZmlraDNm",
      "twitter": "https://x.com/kemenkummaluku/status/1973615651442082298?t=jeHu-QdyxiBD8Ky6NyGhIQ&s=19",
      "facebook": "https://www.facebook.com/share/p/19m7MRS9Uo/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de270d34777c0820506094/berikan-penguatan-saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "terasmaluku": "https://terasmaluku.com/daerahku/2025/10/02/saiful-sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/pppk-kanwil-kemenkum-maluku-tak-sekadar-bertugas/",
      "rri": "https://rri.co.id/ambon/daerah/1876869/sahri-pppk-bukan-sekadar-bertugas-tapi-menghidupkan-semangat-baru",
      "id": 4
    },
    {
      "judul": "Tertib Administrasi, Ratusan Arsip Fidusia dan Fasilitatif Kemenkum Maluku Dimusnahkan",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/tertib-administrasi-ratusan-arsip-fidusia-dan-fasilitatif-kemenkum-maluku-dimusnahkan",
      "instagram": "https://www.instagram.com/p/DPTHYQUksJV/?igsh=bTZkYW9xdGJ5NWZj",
      "twitter": "https://x.com/kemenkummaluku/status/1973658138479042835?t=PmBHbNat_18jfbSi9Jyq2g&s=19",
      "facebook": "https://www.facebook.com/share/p/1Dsiu6MSXa/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de39f8c925c476a7621f62/tertib-administrasi-ratusan-arsip-fidusia-dan-fasilitatif-kemenkum-maluku-dimusnahkan",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/ratusan-arsip-fidusia-fasilitatif-kanwil-kemenkum-maluku-dimusnahkan/",
      "rri": "https://rri.co.id/ambon/daerah/1876878/ratusan-arsip-fidusia-fasilitatif-kemenkum-maluku-dimusnahkan"
    },
    {
      "judul": "Kemenkum Maluku Fokus Tekan Deviasi Anggaran di Triwulan IV: RPD Disusun Lebih Realistis dan Tepat Sasaran",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-fokus-tekan-deviasi-anggaran-di-triwulan-iv-rpd-disusun-lebih-realistis-dan-tepat-sasaran",
      "instagram": "https://www.instagram.com/p/DPTHuDOkgGn/?igsh=Mzh3ZDZ3N3Nlb2lm",
      "twitter": "https://x.com/kemenkummaluku/status/1973658138479042835?t=PmBHbNat_18jfbSi9Jyq2g&s=19",
      "facebook": "https://www.facebook.com/share/p/17MPCSe1Du/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de48a634777c11a502a295/kemenkum-maluku-fokus-tekan-deviasi-anggaran-di-triwulan-iv-rpd-disusun-lebih-realistis-dan-tepat-sasaran",
      "terasmaluku": "https://rri.co.id/ambon/daerah/1876889/rencana-penarikan-dana-disusun-lebih-realistis-tepat-sasaran",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/kanwil-kemenkum-maluku-fokus-tekan-deviasi-anggaran-di-triwulan-iv/",
      "rri": ""
    },
    {
      "judul": "Kanwil Kemenkum Maluku Ikuti Sosialisasi KUHP Nasional",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional",
      "instagram": "https://www.instagram.com/p/DPTIq5sEtZa/?igsh=MjZ1c3NpODdpd3V0",
      "twitter": "https://x.com/kemenkummaluku/status/1973658519011467699?t=IB9IsCbvFlqAXwkmO4FF5g&s=19",
      "facebook": "https://www.facebook.com/share/p/1D1ZKmrAgr/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de58aa34777c68553eb103/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional",
      "terasmaluku": "https://terasmaluku.com/nasional/2025/10/02/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/02/kanwil-kemenkum-maluku-ikuti-sosialisasi-kuhp-nasional/",
      "rri": ""
    },
    {
      "judul": "Kemenkum Maluku Ikuti Sosialisasi Pelayanan Publik Ramah Kelompok Rentan",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kemenkum-maluku-ikuti-sosialisasi-pelayanan-publik-ramah-kelompok-rentan",
      "instagram": "https://www.instagram.com/p/DPTeRZ_kmEY/?igsh=ZTJlbzFua3kzdTB4*",
      "twitter": "https://x.com/kemenkummaluku/status/1973704104171192653?t=1NXAX1xI-GtmhTeKmPi1wA&s=19",
      "facebook": "https://www.facebook.com/share/p/1AKzKQTz6m/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de6bc534777c5da621a8d3/kemenkum-maluku-ikuti-sosialisasi-pelayanan-publik-ramah-kelompok-rentan",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1876900/kemenkum-maluku-ikuti-sosialisasi-pelayanan-publik-ramah-kelompok-rentan"
    },{
      "judul": "Hari Pertama Maluku Manggurebe : Kemenkum Maluku Hadirkan Pelayanan Hukum Langsung ke Masyarakat",
      "tanggal": "2-10-2025",
      "hari": 2,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/hari-pertama-maluku-manggurebe-kemenkum-maluku-hadirkan-pelayanan-hukum-langsung-ke-masyarakat",
      "instagram": "https://www.instagram.com/p/DPTp-lMkju4/?igsh=MTB5aXN1emdvd2RseQ== ",
      "twitter": "https://x.com/kemenkummaluku/status/1973729529085800591?t=8uMfGdSP5fll4FaTUsED_g&s=19",
      "facebook": "https://www.facebook.com/share/p/1MaqBiJfUi/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68de7f12ed64156ca260cc93/hari-pertama-maluku-manggurebe-kemenkum-maluku-hadirkan-pelayanan-hukum-langsung-ke-masyarakat",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Kanwil Kemenkum Maluku Dukung Sinergi Ekonomi Kreatif pada Pembukaan Maluku Manggurebe 2025",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kanwil-kemenkum-maluku-dukung-sinergi-ekonomi-kreatif-pada-pembukaan-maluku-manggurebe-2025",
      "instagram": "https://www.instagram.com/p/DPWos0QktvQ/?igsh=djM4d2x6d3Bza3o4",
      "twitter": "https://x.com/kemenkummaluku/status/1974152360466526261?t=BfiuBnXxpXs0MH8wqKxYiQ&s=19",
      "facebook": "https://www.facebook.com/share/p/17HY1AKZo2/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68df9ffec925c436647bb3d5/kanwil-kemenkum-maluku-dukung-sinergi-ekonomi-kreatif-pada-pembukaan-maluku-manggurebe-2025",
      "terasmaluku": "https://terasmaluku.com/ekonomi/2025/10/03/kanwil-kemenkum-maluku-dukung-sinergi-ekonomi-kreatif-pada-maluku-manggurebe-2025/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1878417/kanwil-kemenkum-dukung-sinergi-ekonomi-kreatif-maluku-manggurebe-2025"
    },
    {
      "judul": "Booth Kemenkum Maluku di Maluku Manggurebe 2025 Dikunjungi Deputi BI dan Kepala OJK Maluku",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/booth-kemenkum-maluku-di-maluku-manggurebe-2025-dikunjungi-deputi-bi-dan-kepala-ojk-maluku",
      "instagram": "https://www.instagram.com/p/DPWpKqGEnuC/?igsh=bTdzeGhhcjd3Z3ly",
      "twitter": "https://x.com/kemenkummaluku/status/1974152555891691935?t=f-sGV54_QyxIAwxau_P_nA&s=19",
      "facebook": "https://www.facebook.com/share/p/1EzqX2Dkmi/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dfaec6ed64151bd752b8a2/booth-kemenkum-maluku-di-maluku-manggurebe-2025-dikunjungi-deputi-bi-dan-kepala-ojk-maluku",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/03/booth-kanwil-kemenkum-di-maluku-manggurebe-2025-dikunjungi-deputi-bi-kepala-ojk/",
      "rri": "https://rri.co.id/ambon/daerah/1878625/booth-kemenkum-dikunjungi-deputi-bi-kepala-ojk"
    },
     {
      "judul": "Booth Layanan Kemenkum Maluku Ramai Dikunjungi di Hari Kedua Maluku Manggurebe 2025",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/booth-layanan-kemenkum-maluku-ramai-dikunjungi-di-hari-kedua-maluku-manggurebe-2025",
      "instagram": "https://www.instagram.com/p/DPWpYLxkjia/?igsh=cXdkYjZucDVlYzZo",
      "twitter": "https://x.com/kemenkummaluku/status/1974153021706940693?t=TYXUXk9-z2W7wPrJUS-t9w&s=19",
      "facebook": "https://www.facebook.com/share/p/17J3BjjWKd/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68dfe9ed34777c5c654b12a4/booth-layanan-kemenkum-maluku-ramai-dikunjungi-di-hari-kedua-maluku-manggurebe-2025",
      "terasmaluku": "https://terasmaluku.com/ekonomi/2025/10/03/booth-layanan-kemenkum-maluku-ramai-dikunjungi-warga-di-maluku-manggurebe-2025/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/03/booth-layanan-kanwil-kemenkum-ramai-dikunjungi-di-hari-kedua-maluku-manggurebe-2025/",
      "rri": "https://rri.co.id/ambon/daerah/1878639/booth-maluku-manggurebe-kemenkum-ramai-dikunjungi-hari-kedua"
    },
    {
      "judul": "Semangat Kolaborasi, Kakanwil Kementerian Hukum Maluku Sambut Kedatangan Komisi XIII DPR RI",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/semangat-kolaborasi-kakanwil-kementerian-hukum-maluku-sambut-kedatangan-komisi-xiii-dpr-ri",
      "instagram": "https://www.instagram.com/p/DPWpk38krsm/?igsh=MXVjdXQwMDRybGh3bw==",
      "twitter": "https://x.com/kemenkummaluku/status/1974153317698904442?t=KmwyUwMf_NGfdhFZeHaAHw&s=19",
      "facebook": "https://www.facebook.com/share/p/15g9kXRWmB/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e000e434777c577a092062/semangat-kolaborasi-kakanwil-kementerian-hukum-maluku-sambut-kedatangan-komisi-xiii-dpr-ri",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/03/kakanwil-kementerian-hukum-maluku-sambut-kedatangan-komisi-xiii-dpr-ri/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1879330/kakanwil-kemenkum-maluku-sambut-kedatangan-komisi-xiiidpr-ri"
    },
    {
      "judul": "Kakanwil Kemenkum Maluku Paparkan Isu Strategis di Hadapan Komisi XIII DPR RI",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/kakanwil-kemenkum-maluku-paparkan-isu-strategis-di-hadapan-komisi-xiii-dpr-ri",
      "instagram": "https://www.instagram.com/p/DPWqBqGkvkG/?igsh=dWEwcm5pM2UyMnl3",
      "twitter": "https://x.com/kemenkummaluku/status/1974153683429658850?t=T0isZSrr912tyKg9F7LX_Q&s=19",
      "facebook": "https://www.facebook.com/share/p/1GDE69i3Bi/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e00efb34777c56fd1cbdf2/kakanwil-kemenkum-maluku-paparkan-isu-strategis-di-hadapan-komisi-xiii-dpr-ri",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/04/kakanwil-kemenkum-maluku-paparkan-isu-strategis-di-hadapan-komisi-xiii-dpr-ri/",
      "malukuterkini": "",
      "rri": "https://rri.co.id/ambon/daerah/1879911/kakanwil-kemenkum-maluku-paparkan-isu-strategis-ke-komisi-xiii-dpr-ri"
    },
    {
      "judul": "16 Kali Berturut-Turut Raih WTP, Kemenkumham Tutup Perjalanan Dengan Catatan Emas",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/16-kali-berturut-turut-raih-wtp-kemenkumham-tutup-perjalanan-dengan-catatan-emas",
      "instagram": "https://www.instagram.com/p/DPW4vK5k_FK/?img_index=2&igsh=MWtzdndjYzQzZWcwMA==",
      "twitter": "https://x.com/kemenkummaluku/status/1974186025460322623?t=OQUlz_K1nyXqSZmeTm-pkA&s=19",
      "facebook": "https://www.facebook.com/share/p/1GMx6ut2Ax/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e01f3a34777c71d44808d4/16-kali-berturut-turut-raih-wtp-kemenkumham-tutup-perjalanan-dengan-catatan-emas",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "WTP ke-16, Akhir 'Manis' Kemenkumham Sebelum Transformasi Kelembagaan",
      "tanggal": "3-10-2025",
      "hari": 3,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/wtp-ke-16-akhir-manis-kemenkumham-sebelum-transformasi-kelembagaan",
      "instagram": "https://www.instagram.com/p/DPW5m2Hk3Fn/?img_index=1&igsh=c3VqbXN5ZjlhejY4",
      "twitter": "https://x.com/kemenkummaluku/status/1974186025460322623?t=Fp7yU0yqmWEHJGYKbI6Rkg&s=19",
      "facebook": "https://www.facebook.com/share/p/19rmuboj9b/",
      "kompasiana": "",
      "terasmaluku": "",
      "malukuterkini": "",
      "rri": ""
    },
    {
      "judul": "Saiful Sahri Dampingi Komisi XIII DPR RI Tinjau Upt Pemasyarakatan dan Imigrasi di Ambon",
      "tanggal": "4-10-2025",
      "hari": 4,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/saiful-sahri-dampingi-komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi-di-ambon",
      "instagram": "https://www.instagram.com/p/DPYbNhREva8/?igsh=MW5vMGI5bjVkb2szZg==",
      "twitter": "https://x.com/kemenkummaluku/status/1974402112202395763?t=6hOvk2pjlSvq6AtCm7YBgw&s=19",
      "facebook": "https://www.facebook.com/share/p/1BnEXVk5mp/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e0da6c34777c47911a5bc5/saiful-sahri-dampingi-komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi-di-ambon",
      "terasmaluku": "https://terasmaluku.com/ambonku/2025/10/04/saiful-sahri-dampingi-komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi/",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/04/kakanwil-kemenkum-maluku-dampingi-dpr-ri-tinjau-upt-pemasyarakatan-dan-imigrasi-di-ambon/",
      "rri": "https://rri.co.id/ambon/daerah/1880828/komisi-xiii-dpr-ri-tinjau-upt-pemasyarakatan-imigrasi-ambon"
    },
    {
      "judul": "Anggota DPR RI Kunjungi Booth Layanan Kemenkum Maluku di Acara Maluku Manggurebe 2025",
      "tanggal": "4-10-2025",
      "hari": 4,
      "bulan": 10,
      "tahun": 2025,
      "website": "https://maluku.kemenkum.go.id/berita-utama/anggota-dpr-ri-kunjungi-booth-layanan-kemenkum-maluku-di-acara-maluku-manggurebe-2025",
      "instagram": "https://www.instagram.com/p/DPYbtV0EnRV/?igsh=eTQ1YnN6MzdzOGo5",
      "twitter": "https://x.com/kemenkummaluku/status/1974402317660414403?t=lDiwwwKg-pK3xcuxbDhd_g&s=19",
      "facebook": "https://www.facebook.com/share/p/1BQj3vhEkN/",
      "kompasiana": "https://www.kompasiana.com/kanwilkemenkumhammaluku3864/68e0e906ed64157bef753905/anggota-dpr-ri-kunjungi-booth-layanan-kemenkum-maluku-di-acara-maluku-manggurebe-2025",
      "terasmaluku": "",
      "malukuterkini": "https://www.malukuterkini.com/2025/10/04/anggota-dpr-ri-kunjungi-booth-layanan-kanwil-kemenkum-di-maluku-manggurebe-2025/",
      "rri": "https://rri.co.id/ambon/daerah/1880734/anggota-dprri-kunjungibooth-layanan-kemenkum-di-maluku-manggurebe"
    }
    
  ]